import { registerFormalQuestionCorpusP5 } from './interview-formal-corpus-p5.ts';
import { registerAuditedInterviewSources, compileInterviewDocument } from './interview-source-compiler.ts';
type F={id:string;name:string;signalId:string;topicId:string;methodKey:string;intent:string;decisionPattern:string}; type Q={id:string;familyId:string;methodKey:string;text:string;difficulty:'SENIOR'|'STAFF';tags:string;pressure:string};
const FAMILIES:F[]=[
{id:'qf.coding-typescript-modeling',name:'TypeScript Type Modeling',signalId:'signal.baseline',topicId:'coding.typescript',methodKey:'ts',intent:'类型建模与运行时边界',decisionPattern:'Runtime Shape → Static Model → Narrow → Verify'},
{id:'qf.coding-async-concurrency',name:'Async / Concurrency Coding',signalId:'signal.baseline',topicId:'coding.async-concurrency',methodKey:'async',intent:'异步控制流、并发上限与竞态',decisionPattern:'Workload → Async Boundary → Concurrency → Backpressure'},
{id:'qf.coding-testing-design',name:'Testing Design',signalId:'signal.judgment',topicId:'coding.testing',methodKey:'test',intent:'测试边界、隔离与失败诊断',decisionPattern:'Risk → Contract → Test Level → Failure Evidence'},
{id:'qf.backend-auth-boundary',name:'Authentication / Authorization Boundary',signalId:'signal.risk',topicId:'backend.auth',methodKey:'auth',intent:'身份、权限与 fail-closed',decisionPattern:'Identity → Resource/Action → Policy → Enforce → Audit'},
{id:'qf.backend-cache-consistency',name:'Cache Consistency',signalId:'signal.judgment',topicId:'backend.cache',methodKey:'cache',intent:'缓存失效与 source of truth',decisionPattern:'Read → Source → Cache → Invalidate → Degrade'},
{id:'qf.backend-concurrency-control',name:'Backend Concurrency Control',signalId:'signal.judgment',topicId:'backend.concurrency',methodKey:'concurrent',intent:'并发冲突、资源控制与重试',decisionPattern:'Invariant → Conflict → Control → Retry/Reject'},
{id:'qf.frontend-engineering-build',name:'Frontend Build / Delivery Engineering',signalId:'signal.judgment',topicId:'frontend.engineering',methodKey:'build',intent:'构建目标、兼容与发布契约',decisionPattern:'Target → Build → Artifact → Deploy → Verify'},
{id:'qf.system-data-state-authority',name:'System Data / State Authority',signalId:'signal.ceiling',topicId:'system-design.data-state',methodKey:'state',intent:'数据 authority 与状态生命周期',decisionPattern:'Invariant → Owner → Transition → Persist → Recover'},
{id:'qf.system-consistency-boundary',name:'System Consistency Boundary',signalId:'signal.ceiling',topicId:'system-design.consistency',methodKey:'consistency',intent:'一致性需求与冲突成本',decisionPattern:'Invariant → Consistency → Isolation → Conflict → Recovery'},];
const QUESTIONS:Q[]=[
{id:'fq6.coding-ts.01',familyId:'qf.coding-typescript-modeling',methodKey:'ts',difficulty:'SENIOR',tags:'typescript union narrowing runtime validation',text:'一个 API 返回多种状态结构时，你会怎样用 discriminated union 和 narrowing 建模，而不是到处写可选字段？',pressure:'TypeScript 编译通过，为什么外部 JSON 仍需要 runtime validation？'},
{id:'fq6.coding-ts.02',familyId:'qf.coding-typescript-modeling',methodKey:'ts',difficulty:'SENIOR',tags:'typescript generic constraints',text:'什么时候应该用 generic，什么时候明确写具体 union 或接口反而更安全？',pressure:'过度泛型为什么可能把业务约束藏进类型技巧里？'},
{id:'fq6.coding-async.01',familyId:'qf.coding-async-concurrency',methodKey:'async',difficulty:'SENIOR',tags:'async concurrency backpressure promise',text:'需要并发处理一千个异步任务时，你为什么不会直接 Promise.all 全部启动？',pressure:'任务都是 async，为什么仍可能压垮 Event Loop 或下游？'},
{id:'fq6.coding-async.02',familyId:'qf.coding-async-concurrency',methodKey:'async',difficulty:'SENIOR',tags:'async race stale result cancellation',text:'两个异步操作可能乱序完成并写同一状态，你会怎样防止旧结果覆盖新结果？',pressure:'只加 debounce 为什么不等于解决竞态？'},
{id:'fq6.coding-test.01',familyId:'qf.coding-testing-design',methodKey:'test',difficulty:'SENIOR',tags:'testing unit integration e2e async',text:'异步服务逻辑同时有纯计算、数据库和 HTTP 依赖，你会怎么划分单测、集成测试和端到端验证？',pressure:'三个层级都测同一 happy path 为什么仍可能浪费？'},
{id:'fq6.coding-test.02',familyId:'qf.coding-testing-design',methodKey:'test',difficulty:'SENIOR',tags:'testing harness flaky race',text:'测试偶发失败时，你怎么区分产品竞态、共享状态污染、时间依赖和测试 Harness 自身问题？',pressure:'为什么重跑就过不能直接标记 flaky 后忽略？'},
{id:'fq6.backend-auth.01',familyId:'qf.backend-auth-boundary',methodKey:'auth',difficulty:'SENIOR',tags:'authentication authorization least privilege',text:'用户已经登录成功，为什么服务端仍然必须在每次敏感请求上做 authorization？',pressure:'前端隐藏按钮为什么不是后端权限控制？'},
{id:'fq6.backend-auth.02',familyId:'qf.backend-auth-boundary',methodKey:'auth',difficulty:'STAFF',tags:'authorization rbac abac policy audit',text:'RBAC 出现大量例外角色时，你如何判断继续扩角色还是转向更细粒度 policy？',pressure:'权限越灵活，为什么审计和 deny-by-default 越重要？'},
{id:'fq6.backend-cache.01',familyId:'qf.backend-cache-consistency',methodKey:'cache',difficulty:'SENIOR',tags:'cache invalidation source truth stale',text:'数据库更新后缓存应该何时失效？你怎样定义 source of truth 和允许的 stale window？',pressure:'把 TTL 设很短为什么不等于解决缓存一致性？'},
{id:'fq6.backend-cache.02',familyId:'qf.backend-cache-consistency',methodKey:'cache',difficulty:'SENIOR',tags:'cache stampede invalidation fallback',text:'热点 key 失效时大量请求同时回源，你会怎样处理 cache stampede？',pressure:'加一把全局锁为什么可能制造新的可用性问题？'},
{id:'fq6.backend-concurrency.01',familyId:'qf.backend-concurrency-control',methodKey:'concurrent',difficulty:'SENIOR',tags:'concurrency optimistic lock transaction',text:'两个请求同时修改同一业务对象时，你会何时选择数据库约束、乐观锁、悲观锁或串行队列？',pressure:'只在应用进程里加 mutex，多实例后为什么可能失效？'},
{id:'fq6.backend-concurrency.02',familyId:'qf.backend-concurrency-control',methodKey:'concurrent',difficulty:'STAFF',tags:'concurrency fairness limit backpressure',text:'面对有限连接池和下游容量，你怎么设计公平性、限流和 backpressure？',pressure:'并发数越高为什么吞吐可能反而下降？'},
{id:'fq6.frontend-build.01',familyId:'qf.frontend-engineering-build',methodKey:'build',difficulty:'SENIOR',tags:'vite build target compatibility base path',text:'前端项目从 dev server 到 production build，哪些假设会变化？你如何验证浏览器目标、资源路径和 artifact？',pressure:'本地 dev 正常为什么不能证明 CDN 或子路径部署正常？'},
{id:'fq6.frontend-build.02',familyId:'qf.frontend-engineering-build',methodKey:'build',difficulty:'SENIOR',tags:'frontend dependency build compatibility release',text:'依赖升级让 bundle 变大并出现兼容问题，你会怎样区分构建配置、依赖内容和浏览器目标？',pressure:'锁回旧版本为什么只是止损？'},
{id:'fq6.system-state.01',familyId:'qf.system-data-state-authority',methodKey:'state',difficulty:'STAFF',tags:'system state authority source truth persistence',text:'数据库、缓存、内存状态和消息事件都保存状态时，你怎么定义谁拥有 authority？',pressure:'两个地方都允许写同一业务状态会有什么恢复问题？'},
{id:'fq6.system-state.02',familyId:'qf.system-data-state-authority',methodKey:'state',difficulty:'STAFF',tags:'state durable transition recovery',text:'设计长流程时，哪些状态必须持久化，哪些可以只存在进程内或模型上下文？',pressure:'进程重启后必须继续时，什么状态才算 durable enough？'},
{id:'fq6.system-consistency.01',familyId:'qf.system-consistency-boundary',methodKey:'consistency',difficulty:'STAFF',tags:'consistency transaction isolation invariant',text:'系统设计里你怎样从业务不变量决定强一致、事务隔离还是最终一致，而不是先选技术？',pressure:'所有地方都强一致为什么可能更慢但仍不更正确？'},
{id:'fq6.system-consistency.02',familyId:'qf.system-consistency-boundary',methodKey:'consistency',difficulty:'STAFF',tags:'consistency conflict retry serialization',text:'高并发事务为了保持一致性不断冲突重试时，你怎样判断该调整数据模型、事务边界还是协调方式？',pressure:'重试成功率很高为什么仍可能隐藏设计问题？'},];
const METHODS:any[]=[['ts','source.typescript-docs','TypeScript narrowing 和 generics 用静态类型表达运行时分支与可复用约束。'],['async','source.nodejs-async','Node Event Loop / Worker Pool 要求单次工作保持有界；异步不等于无限并发。'],['test','source.node-test','Node test runner 明确同步、Promise、隔离、并发与 setup/teardown 的执行语义。'],['auth','source.owasp-auth','Authorization 区别于 authentication，应 least privilege、deny by default 并每请求校验。'],['cache','source.redis-cache','缓存需要明确 source of truth 与数据变化后的 invalidation。'],['concurrent','source.postgresql-docs','并发事务围绕业务不变量选择隔离、锁和重试。'],['build','source.vite-docs','Production build 明确 browser target、base path、artifact 与部署契约。'],['state','source.postgresql-docs','持久化状态和事务约束用于维护业务不变量与 durable state。'],['consistency','source.postgresql-docs','Serializable 提供强隔离但可能冲突并要求应用重试。']];
function units(db:any,now:string){registerAuditedInterviewSources(db,now);const m=new Map<string,string>();for(const [key,sourceId,text] of METHODS){const s:any=db.prepare('SELECT canonical_url,name FROM interview_sources WHERE id=?').get(sourceId);if(!s)throw new Error(`P5B_SOURCE_MISSING:${sourceId}`);const c:any=compileInterviewDocument(db,{sourceId,title:`P5 Core Expansion｜${s.name}`,canonicalUrl:s.canonical_url,capturedAt:now,units:[{locator:`p5b/${key}`,kind:'TECHNIQUE',text}]});m.set(key,c.units[0].unitId)}return m}
export function registerFormalQuestionCorpusP5B(db:any,now=new Date().toISOString()){registerFormalQuestionCorpusP5(db,now);const u=units(db,now);db.exec('BEGIN;');try{const f=db.prepare(`INSERT INTO interview_question_families(id,name,primary_signal_id,normalized_intent,decision_pattern,lifecycle,version,created_at,updated_at) VALUES(?,?,?,?,?,'ACTIVE',1,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,primary_signal_id=excluded.primary_signal_id,normalized_intent=excluded.normalized_intent,decision_pattern=excluded.decision_pattern,lifecycle='ACTIVE',updated_at=excluded.updated_at`);for(const x of FAMILIES)f.run(x.id,x.name,x.signalId,x.intent,x.decisionPattern,now,now);const q=db.prepare(`INSERT INTO interview_questions(id,question_family_id,source_unit_id,canonical_text,language,difficulty,lifecycle,created_at,updated_at) VALUES(?,?,?,?,'zh-CN',?,'ACTIVE',?,?) ON CONFLICT(id) DO UPDATE SET source_unit_id=excluded.source_unit_id,canonical_text=excluded.canonical_text,difficulty=excluded.difficulty,lifecycle='ACTIVE',updated_at=excluded.updated_at`);const v=db.prepare(`INSERT INTO interview_question_variants(id,question_id,source_unit_id,text,tone,pressure_mode,language,lifecycle,created_at,updated_at) VALUES(?,?,?,?,'DIRECT','PRESSURE','zh-CN','ACTIVE',?,?) ON CONFLICT(id) DO UPDATE SET source_unit_id=excluded.source_unit_id,text=excluded.text,lifecycle='ACTIVE',updated_at=excluded.updated_at`);const s=db.prepare(`INSERT INTO interview_question_search(item_type,item_id,family_id,text,tags,signal_terms) VALUES('QUESTION',?,?,?,?,?)`);for(const x of QUESTIONS){const z=u.get(x.methodKey)!;q.run(x.id,x.familyId,z,x.text,x.difficulty,now,now);v.run(`fq6v.${x.id.slice(4)}`,x.id,z,x.pressure,now,now);const sig:any=db.prepare(`SELECT s.id,s.name FROM interview_question_families f LEFT JOIN interview_signals s ON s.id=f.primary_signal_id WHERE f.id=?`).get(x.familyId);db.prepare("DELETE FROM interview_question_search WHERE item_type='QUESTION' AND item_id=?").run(x.id);s.run(x.id,x.familyId,`${x.text} ${x.pressure}`,x.tags,`${sig?.id??''} ${sig?.name??''}`)}const a=db.prepare(`INSERT INTO interview_scoring_anchors(id,question_family_id,signal_id,source_unit_id,polarity,observable_behavior,lifecycle,created_at,updated_at) VALUES(?,?,?,?,?,?,'ACTIVE',?,?) ON CONFLICT(id) DO UPDATE SET source_unit_id=excluded.source_unit_id,polarity=excluded.polarity,observable_behavior=excluded.observable_behavior,lifecycle='ACTIVE',updated_at=excluded.updated_at`);for(const x of FAMILIES){const z=u.get(x.methodKey)!;a.run(`anchor.fq6.${x.id.slice(3)}.positive`,x.id,x.signalId,z,'POSITIVE',`能解释 ${x.name} 的机制、约束、失败路径与验证。`,now,now);a.run(`anchor.fq6.${x.id.slice(3)}.negative`,x.id,x.signalId,z,'NEGATIVE',`只背 ${x.name} 名词，无法说明 trade-off 或验证。`,now,now)}db.exec('COMMIT;');return{families:9,questions:18,variants:18,anchors:18,methodUnits:9}}catch(e){try{db.exec('ROLLBACK;')}catch{}throw e}}
