PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, version INTEGER NOT NULL UNIQUE, name TEXT NOT NULL, checksum TEXT NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS providers (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS jobs (
 id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES providers(id), external_job_id TEXT, identity_fingerprint TEXT NOT NULL, origin_kind TEXT NOT NULL CHECK(origin_kind IN ('LIVE_DISCOVERY','HISTORICAL_IMPORT')), source_url TEXT,
 title TEXT NOT NULL, company TEXT NOT NULL, city TEXT, district TEXT, address TEXT, salary_min INTEGER, salary_max INTEGER, salary_months INTEGER, salary_text TEXT, experience_min INTEGER, experience_max INTEGER, experience_text TEXT, education_level TEXT, education_text TEXT, employment_type TEXT, role_family TEXT, seniority TEXT, jd_text TEXT NOT NULL DEFAULT '', recruiter_name TEXT, recruiter_activity TEXT, published_at TEXT,
 current_verification_status TEXT NOT NULL CHECK(current_verification_status IN ('NEW','LISTED','LIVE_CONFIRMED','RECRUITER_CONFIRMED','UNKNOWN','BLOCKED','STALE','CLOSED')), last_verified_at TEXT, education_risk TEXT NOT NULL CHECK(education_risk IN ('LOW','MEDIUM','HIGH','VERY_HIGH')), education_risk_reason TEXT, is_viewed INTEGER NOT NULL DEFAULT 0 CHECK(is_viewed IN (0,1)), first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_jobs_provider_external ON jobs(provider_id, external_job_id) WHERE external_job_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_jobs_fingerprint ON jobs(identity_fingerprint);
CREATE INDEX IF NOT EXISTS ix_jobs_filters ON jobs(provider_id, city, education_risk, current_verification_status, first_seen_at, last_verified_at);
CREATE TABLE IF NOT EXISTS job_snapshots (id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, captured_at TEXT NOT NULL, source_url TEXT, title TEXT, company TEXT, salary_text TEXT, experience_text TEXT, education_text TEXT, location_text TEXT, jd_text TEXT, recruiter_activity_text TEXT, content_hash TEXT NOT NULL, raw_payload_ref TEXT, created_at TEXT NOT NULL, UNIQUE(job_id,content_hash));
CREATE INDEX IF NOT EXISTS ix_snapshots_timeline ON job_snapshots(job_id,captured_at DESC);
CREATE TABLE IF NOT EXISTS job_verifications (id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, verified_at TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('NEW','LISTED','LIVE_CONFIRMED','RECRUITER_CONFIRMED','UNKNOWN','BLOCKED','STALE','CLOSED')), confidence REAL, method TEXT, page_exists INTEGER, closed_signal INTEGER, contact_action_available INTEGER, apply_action_available INTEGER, recruiter_active INTEGER, recruiter_confirmed INTEGER, evidence_summary TEXT, error_code TEXT, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ix_verifications_timeline ON job_verifications(job_id,verified_at DESC);
CREATE TABLE IF NOT EXISTS resumes (id TEXT PRIMARY KEY, name TEXT NOT NULL, direction TEXT NOT NULL, source_path TEXT, snapshot_path TEXT, content TEXT, content_hash TEXT NOT NULL, version_label TEXT NOT NULL, is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS match_baselines (id TEXT PRIMARY KEY, name TEXT NOT NULL, direction TEXT NOT NULL, description TEXT, is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS match_terms (id TEXT PRIMARY KEY, baseline_id TEXT NOT NULL REFERENCES match_baselines(id) ON DELETE CASCADE, term TEXT NOT NULL, match_type TEXT NOT NULL CHECK(match_type IN ('STRONG_BOOST','BOOST','INCLUDE','RISK','STRONG_RISK','EXCLUDE')), category TEXT, weight INTEGER NOT NULL DEFAULT 0, notes TEXT, is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS job_match_results (id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, baseline_id TEXT NOT NULL REFERENCES match_baselines(id) ON DELETE CASCADE, rule_score INTEGER NOT NULL CHECK(rule_score BETWEEN 0 AND 100), semantic_score REAL, final_score INTEGER NOT NULL CHECK(final_score BETWEEN 0 AND 100), excluded INTEGER NOT NULL CHECK(excluded IN (0,1)), education_risk TEXT NOT NULL, matched_terms_json TEXT NOT NULL DEFAULT '[]', risk_terms_json TEXT NOT NULL DEFAULT '[]', excluded_terms_json TEXT NOT NULL DEFAULT '[]', explanation_json TEXT NOT NULL DEFAULT '{}', evaluator_version TEXT NOT NULL, evaluated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ix_match_baseline_score ON job_match_results(baseline_id,final_score DESC);
CREATE INDEX IF NOT EXISTS ix_match_job_time ON job_match_results(job_id,evaluated_at DESC);
CREATE TABLE IF NOT EXISTS search_runs (id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES providers(id), query TEXT, city TEXT, filters_json TEXT, started_at TEXT NOT NULL, finished_at TEXT, status TEXT NOT NULL, found_count INTEGER NOT NULL DEFAULT 0, new_count INTEGER NOT NULL DEFAULT 0, updated_count INTEGER NOT NULL DEFAULT 0, duplicate_count INTEGER NOT NULL DEFAULT 0, blocked_count INTEGER NOT NULL DEFAULT 0, error_summary TEXT, created_at TEXT NOT NULL);
