import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { openDatabase } from '../server/db.ts';
import { executeInterviewRuntimeCommand } from '../server/interview-runtime-cli.ts';
import { createInterviewRuntimeHost } from '../server/interview-runtime-host.ts';

const plan={id:'mission.runtime.tech1',routeId:'route.ai-agent-devtools',sceneId:'scene.tech1',purpose:'runtime integration',roundBudgetSeconds:1800,completionRule:'MANDATORY_PHASES_AND_FOCUS',archetype:{id:'engineer',roleName:'Engineer',pressureBand:'MEDIUM',hintPolicy:'BOUNDED',interruptionPolicy:'TIMEBOXED'},probePolicy:{id:'probe',maxConsecutiveSameSignal:2,maxConsecutiveSameFamily:2,stopOnExplicitUnknown:true},focusSignals:[{signalId:'signal.truthfulness',priority:'P0',required:true,targetState:'CONFIRMED',minimumEvidenceCount:1,maxProbeDepth:2},{signalId:'signal.judgment',priority:'P1',required:true,targetState:'CONFIRMED',minimumEvidenceCount:1,maxProbeDepth:2}],incidentalSignals:[],phases:[{id:'PROJECT',order:1,budgetSeconds:1200,focusSignalIds:['signal.truthfulness','signal.judgment'],mandatory:true}]};
function start(db:any,id='r.start'){return executeInterviewRuntimeCommand(db,{op:'interview.start_session',input:{requestId:id,mode:'TEXT',routeId:'route.ai-agent-devtools',sceneId:'scene.tech1'}});}
async function withHost(fn:(base:string,host:any)=>Promise<void>){const host=createInterviewRuntimeHost({dbPath:':memory:'});host.server.listen(0,'127.0.0.1');await once(host.server,'listening');const addr:any=host.server.address();try{await fn(`http://127.0.0.1:${addr.port}`,host);}finally{await host.close();}}
async function post(base:string,path:string,body:any){return await (await fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})).json();}

test('TP-DIR4-001 Runtime status exposes Director operations without removing existing operations',()=>{const db=openDatabase(':memory:');try{const s:any=executeInterviewRuntimeCommand(db,{op:'status'});assert.deepEqual(s.directorOperations.sort(),['interview.director_decide','interview.director_finalize','interview.director_get_state','interview.director_prepare_session']);assert.ok(s.operations.includes('interview.start_session'));}finally{db.close();}});

test('TP-DIR4-002 prepare through Runtime opts only that Session into strategy.director.v1',()=>{const db=openDatabase(':memory:');try{const s=start(db);executeInterviewRuntimeCommand(db,{op:'interview.director_prepare_session',input:{requestId:'r.prepare',sessionId:s.sessionId,plan}});assert.equal((db.prepare('SELECT strategy_version FROM interview_sessions WHERE id=?').get(s.sessionId) as any).strategy_version,'strategy.director.v1');}finally{db.close();}});

test('TP-DIR4-003 next_turn accepts Director targetSignalId and still returns Corpus question',()=>{const db=openDatabase(':memory:');try{const s=start(db);const next:any=executeInterviewRuntimeCommand(db,{op:'interview.next_turn',input:{requestId:'r.next',sessionId:s.sessionId,targetSignalId:'signal.judgment'}});assert.equal(next.state.targetSignal,'signal.judgment');assert.ok(next.prompt.questionId);assert.ok(next.prompt.primaryQuestion.length>0);}finally{db.close();}});

test('TP-DIR4-004 Director Host continue performs observe→decide→next without caller choosing desiredAction',async()=>{await withHost(async(base,host)=>{const s:any=(await post(base,'/tool',{op:'interview.start_session',input:{requestId:'h.start',mode:'TEXT',routeId:'route.ai-agent-devtools',sceneId:'scene.tech1'}})).result;await post(base,'/tool',{op:'interview.director_prepare_session',input:{requestId:'h.prepare',sessionId:s.sessionId,plan}});const first:any=(await post(base,'/tool',{op:'interview.next_turn',input:{requestId:'h.next1',sessionId:s.sessionId,targetSignalId:'signal.truthfulness'}})).result;const body:any=await post(base,'/interview/continue',{observeRequestId:'h.obs1',directorRequestId:'h.dec1',nextRequestId:'h.next2',sessionId:s.sessionId,turnId:first.turnId,answerObservation:{signalUpdate:{signalId:'signal.truthfulness',state:'PROBING',confidence:.5}}});assert.equal(body.ok,true);assert.equal(body.result.director.action,'PROBE_DEPTH');assert.equal(body.result.next.turnIntent,'FOLLOW_UP');});});

test('TP-DIR4-005 Director CLOSE_ROUND returns no next question; legacy continue stays compatible',async()=>{await withHost(async(base,host)=>{const director:any=(await post(base,'/tool',{op:'interview.start_session',input:{requestId:'c.start',mode:'TEXT',routeId:'route.ai-agent-devtools',sceneId:'scene.tech1'}})).result;await post(base,'/tool',{op:'interview.director_prepare_session',input:{requestId:'c.prepare',sessionId:director.sessionId,plan:{...plan,focusSignals:[plan.focusSignals[0]],phases:[{id:'ONLY',order:1,budgetSeconds:1200,focusSignalIds:['signal.truthfulness'],mandatory:true}]}}});host.db.prepare("UPDATE interview_session_signals SET state='CONFIRMED',confidence=.9 WHERE session_id=? AND signal_id='signal.truthfulness'").run(director.sessionId);const first:any=(await post(base,'/tool',{op:'interview.next_turn',input:{requestId:'c.next1',sessionId:director.sessionId}})).result;const closed:any=await post(base,'/interview/continue',{observeRequestId:'c.obs',directorRequestId:'c.dec',nextRequestId:'c.next2',sessionId:director.sessionId,turnId:first.turnId,answerObservation:{}});assert.equal(closed.result.director.action,'CLOSE_ROUND');assert.equal(closed.result.next,null);
const legacy:any=(await post(base,'/tool',{op:'interview.start_session',input:{requestId:'l.start',mode:'TEXT',routeId:'route.ai-agent-devtools',sceneId:'scene.tech1'}})).result;const lfirst:any=(await post(base,'/tool',{op:'interview.next_turn',input:{requestId:'l.next1',sessionId:legacy.sessionId}})).result;const continued:any=await post(base,'/interview/continue',{observeRequestId:'l.obs',nextRequestId:'l.next2',sessionId:legacy.sessionId,turnId:lfirst.turnId,answerObservation:{}});assert.ok(continued.result.observed);assert.ok(continued.result.next);assert.equal('director' in continued.result,false);});});
